### ISSUE TITLE
INSTALL

### ISSUE THREAD

**Issue by g-sichardt** [cenit/GDL#1]
the readme file says "Please see the INSTALL file for details." as well as the python file refers to INSTALL. but in gdl 0.9.5 there is no file called INSTALL or at least I can not find it.

**Comment by cenit** [comment]
Please refer to INSTALL.CMake, which is the only supported installation system

**Comment by g-sichardt** [comment]
thank you.
so please change the lines in the readme and python text files.

**Comment by cenit** [comment]
This repo is just a clone of the official CVS repo. I'm not doing any variation to it
